apiVersion: v1
kind: Pod
metadata:
  name: experiment_1
  namespace: experiment
spec:
  containers:
  - name: experiment_1_container
    image: experiment_1
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"