apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: experiment1
  labels:
    app: experiment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: experiment
  template:
    metadata:
      labels:
        app: experiment
    spec:
      containers:
      - name: experiment1
        image: http://influxdb.test12.wall2-ilabt-iminds-be.wall1.ilabt.iminds.be:5000/experiment1:0.0.1
        env:
        - name: INFLUX_HOST
          value: "influxdb.test12.wall2-ilabt-iminds-be.wall1.ilabt.iminds.be"
        - name: INFLUX_DATABASE
          value: "metrics"
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "2000Mi"